const questions = [
 {id:1,d:'foundations',q:'Which description best matches the handbook definition of systems engineering?',a:['A discipline focused primarily on controlling project cost and schedule','A transdisciplinary and integrative approach that enables successful realization, use, and retirement of engineered systems','A verification method used after system integration','A process for selecting one architecture from a completed trade study'],c:1,e:'The handbook presents SE as transdisciplinary and integrative. It uses systems principles and concepts, plus scientific, technological, and management methods, to enable successful realization, use, and retirement of engineered systems.',r:'Chapter 1, §1.1, pp. 1–2'},
 {id:2,d:'foundations',q:'What is the most accurate relationship between an engineered system and its environment?',a:['The environment is outside the scope of systems engineering','The system is isolated once its boundary is approved','The system interacts with its environment and may include people, products, services, information, processes, and natural elements','Only physical interfaces cross the system boundary'],c:2,e:'The handbook treats engineered systems broadly and emphasizes interaction with their environment. System boundaries and external interfaces matter throughout definition and realization.',r:'Chapter 1, §1.2, pp. 2–12'},
 {id:3,d:'foundations',q:'Why does the handbook stress early systems engineering effort?',a:['Most defects can only be discovered during concept development','A large proportion of life-cycle cost is committed before the same proportion has actually been spent','Technical reviews are prohibited after development begins','Early effort eliminates all future change'],c:1,e:'The handbook illustrates that decisions made early commit much of the total life-cycle cost. Finding and addressing issues earlier is generally less costly and helps reduce technical debt.',r:'Chapter 1, §1.4, pp. 21–23 (Figures 1.3–1.4)'},
 {id:4,d:'foundations',q:'Which sequence gives the six typical life-cycle stages in the handbook’s informative model?',a:['Concept, development, production, utilization, support, retirement','Planning, acquisition, design, build, test, disposal','Concept, architecture, implementation, verification, validation, operation','Need, requirements, design, integration, deployment, maintenance'],c:0,e:'The six typical stages are concept, development, production, utilization, support, and retirement. A real organization may adapt its life-cycle model through tailoring.',r:'Chapter 2, §2.1.2, pp. 26–29'},
 {id:5,d:'foundations',q:'What is the primary role of a decision gate?',a:['To perform detailed design','To provide a point for evaluating maturity and deciding whether and how to proceed','To replace technical reviews and audits','To assign every requirement to a system element'],c:1,e:'Decision gates support governance by evaluating evidence and maturity at key points. Outcomes can include proceeding, redirecting, holding, or stopping work.',r:'Chapter 2, §2.1.3, pp. 29–31'},
 {id:6,d:'foundations',q:'How are system life-cycle processes intended to be applied?',a:['Once each, in the numbered order shown','Only during development and production','Concurrently, iteratively, and recursively as appropriate across life-cycle stages','Only after the life-cycle model has ended'],c:2,e:'The process listing is not a rigid sequence. Processes are applied concurrently, iteratively, and recursively, with other enablers, as the situation requires.',r:'Chapter 2, §2.3.1–2.3.1.2, pp. 39–44'},
 {id:7,d:'processes',q:'Which pair comprises the Agreement Processes?',a:['Acquisition and Supply','Planning and Assessment','Verification and Validation','Operation and Maintenance'],c:0,e:'The Agreement Processes are Acquisition and Supply. They establish agreements between an acquirer and supplier and support fulfillment of those agreements.',r:'Chapter 2, §2.3.2, pp. 44–50'},
 {id:8,d:'processes',q:'Which item is an Organizational Project-Enabling Process?',a:['System Analysis','Knowledge Management','Integration','Stakeholder Needs and Requirements Definition'],c:1,e:'Knowledge Management is one of six Organizational Project-Enabling Processes, alongside life-cycle model, infrastructure, portfolio, human resource, and quality management.',r:'Chapter 2, §2.3.3, pp. 50–70'},
 {id:9,d:'processes',q:'A project team must identify, analyze, treat, and monitor threats and opportunities. Which process directly addresses this?',a:['Decision Management','Risk Management','Measurement','Quality Assurance'],c:1,e:'Risk Management addresses both threats and opportunities across the life cycle, including planning, identification, analysis, treatment, and monitoring.',r:'Chapter 2, §2.3.4.4, pp. 81–87'},
 {id:10,d:'processes',q:'What is the central purpose of Configuration Management?',a:['To approve the business case','To establish and maintain the integrity of identified system and project artifacts over time','To measure stakeholder satisfaction','To determine the preferred system architecture'],c:1,e:'Configuration Management identifies and controls configuration items, manages status, and supports audits so the integrity and traceability of artifacts are maintained.',r:'Chapter 2, §2.3.4.5, pp. 87–91'},
 {id:11,d:'processes',q:'Which process provides objective assurance that processes and products comply with established requirements, plans, and agreements?',a:['Quality Management','Quality Assurance','Project Assessment and Control','Verification'],c:1,e:'Quality Assurance focuses on objective assurance of compliance. Quality Management is the broader organizational enabling process that establishes and monitors quality management practices.',r:'Chapter 2, §2.3.4.8, pp. 98–101'},
 {id:12,d:'processes',q:'Measures of effectiveness (MOEs) are most closely associated with which perspective?',a:['How well the system satisfies operational or mission needs','Whether each design drawing is under configuration control','How many requirements have been written','Whether a supplier invoice was approved'],c:0,e:'MOEs characterize effectiveness from the operational or stakeholder perspective. Measures of performance (MOPs) characterize system performance; technical performance measures track selected parameters during development.',r:'Chapter 2, §2.3.4.7, pp. 93–98'},
 {id:13,d:'technical',q:'What does the Business or Mission Analysis process primarily establish?',a:['Detailed component drawings','The problem or opportunity space and preferred solution classes','Proof that every system requirement is verified','The production schedule'],c:1,e:'Business or Mission Analysis examines problems or opportunities, characterizes the mission/business context, and develops candidate solution classes and a preferred solution class.',r:'Chapter 2, §2.3.5.1, pp. 103–107'},
 {id:14,d:'technical',q:'Which statement best distinguishes stakeholder needs from stakeholder requirements?',a:['Needs express the problem or desired outcome; requirements are transformed, agreed statements suitable to guide the solution','Needs are always quantitative; requirements are always qualitative','Needs belong to suppliers; requirements belong to acquirers','There is no distinction in the handbook'],c:0,e:'Needs capture what stakeholders seek in context. Through analysis, elicitation, and resolution, they are transformed into an agreed set of stakeholder requirements.',r:'Chapter 2, §2.3.5.2, pp. 107–112'},
 {id:15,d:'technical',q:'The System Requirements Definition process transforms:',a:['A detailed design into an architecture','A stakeholder/user-oriented view of desired capabilities into a technical view of a solution','Verification results into validation criteria','A supply agreement into a project plan'],c:1,e:'System Requirements Definition creates the technical view needed to meet operational needs. The result forms a foundation for architecture, design, integration, and verification.',r:'Chapter 2, §2.3.5.3, pp. 112–118'},
 {id:16,d:'technical',q:'Which statement best separates architecture definition from design definition?',a:['Architecture identifies system concepts, structure, and relationships; design provides sufficiently detailed data to realize the solution','Architecture occurs after implementation; design occurs before requirements','Architecture validates stakeholder needs; design verifies the system','The two processes have identical purposes'],c:0,e:'Architecture Definition establishes concepts, properties, principles, structure, and relationships. Design Definition turns architecture and requirements into sufficiently detailed information for implementation.',r:'Chapter 2, §2.3.5.4–2.3.5.5, pp. 118–129'},
 {id:17,d:'technical',q:'What is the purpose of the System Analysis process?',a:['To manufacture system elements','To provide a rigorous basis for resolving technical questions and selecting among alternatives','To transfer the system to the operational environment','To negotiate the acquisition agreement'],c:1,e:'System Analysis supports technical understanding and decision-making by evaluating alternatives, effectiveness, feasibility, risks, and other relevant characteristics.',r:'Chapter 2, §2.3.5.6, pp. 129–134'},
 {id:18,d:'technical',q:'Which pairing is correct?',a:['Verification — intended use; Validation — specified requirements','Verification — specified requirements; Validation — intended use and stakeholder needs','Verification — business case; Validation — configuration baseline','Verification — production; Validation — disposal'],c:1,e:'Verification provides objective evidence that specified requirements are fulfilled. Validation provides objective evidence that the system fulfills business or mission objectives and stakeholder needs in its intended operational environment.',r:'Chapter 2, §2.3.5.9 and §2.3.5.11, pp. 141–149'},
 {id:19,d:'technical',q:'Integration is primarily concerned with:',a:['Combining system elements and demonstrating that their interfaces work together','Approving the preferred solution class','Operating the system in its intended environment','Retiring the system and its enabling systems'],c:0,e:'Integration combines system elements according to the architecture and integration strategy, addressing interfaces and interactions to form complete configurations.',r:'Chapter 2, §2.3.5.8, pp. 137–141'},
 {id:20,d:'technical',q:'What is the focus of the Transition process?',a:['Moving a verified system into its operational environment and establishing readiness for use','Changing stakeholder needs into system requirements','Selecting the system architecture','Correcting every defect found during validation'],c:0,e:'Transition establishes a system in its operational environment and prepares users, operators, and enabling systems so required services can be provided.',r:'Chapter 2, §2.3.5.10, pp. 144–146'},
 {id:21,d:'methods',q:'Which quality characteristic is commonly expressed through reliability, availability, and maintainability?',a:['Agility','Dependability and support-related performance over time','Interoperability only','Affordability only'],c:1,e:'RAM engineering addresses the probability of performing without failure, readiness for use, and ease/effectiveness of restoration and upkeep. The characteristics interact and involve tradeoffs.',r:'Chapter 3, §3.1.8, pp. 176–180'},
 {id:22,d:'methods',q:'What does traceability provide across engineering artifacts?',a:['A substitute for configuration control','Recorded relationships that support consistency, impact analysis, and evidence across levels','A guarantee that requirements will never change','A list of only external interfaces'],c:1,e:'Traceability records relationships among needs, requirements, architecture, design, verification, and other artifacts. It supports completeness, consistency, change impact analysis, and evidence.',r:'Chapter 3, §3.2.3, pp. 201–202'},
 {id:23,d:'methods',q:'When is prototyping most useful according to the handbook?',a:['Only after final validation','When learning, reducing uncertainty, exploring feasibility, or obtaining feedback is valuable','Only for software-intensive systems','As a replacement for all models and analyses'],c:1,e:'Prototypes help teams learn, test assumptions, explore alternatives and feasibility, communicate concepts, and obtain feedback before committing fully to a solution.',r:'Chapter 3, §3.2.2, pp. 200–201'},
 {id:24,d:'methods',q:'The primary purpose of interface management is to:',a:['Eliminate all external systems','Identify, define, control, and maintain consistency of interactions across boundaries','Replace architecture models with contracts','Measure only physical connector dimensions'],c:1,e:'Interface management addresses interactions among system elements and with external entities. It coordinates definitions and changes across affected parties and artifacts.',r:'Chapter 3, §3.2.4, pp. 202–206'},
 {id:25,d:'tailoring',q:'What does tailoring mean in the handbook?',a:['Skipping documentation whenever the schedule is short','Adapting life-cycle processes and activities to suit the organization, project, and system context while preserving necessary outcomes','Applying every process exactly as printed','Changing requirements after verification'],c:1,e:'Tailoring is thoughtful adaptation—not arbitrary omission. It considers context, risk, complexity, life-cycle approach, organizational policy, and applicable agreements or standards.',r:'Chapter 4, §4.1, pp. 215–219'},
 {id:26,d:'tailoring',q:'Which statement best reflects the handbook’s guidance on process rigor?',a:['More process is always safer','Less process is always more agile','The appropriate balance comes from thoughtful tailoring and intelligent application','Process selection should be based only on project budget'],c:2,e:'The handbook warns against both careless shortcuts and process paralysis. The aim is sufficient, value-adding rigor suited to the actual context.',r:'Preface and Chapter 4, §4.1, pp. xix–xxiii, 215–219'},
 {id:27,d:'tailoring',q:'Model-Based Systems Engineering (MBSE) is best described as:',a:['Using a model only to create final illustrations','The formalized application of modeling to support requirements, design, analysis, verification, and validation across the life cycle','Replacing all engineering judgment with simulation','A life-cycle stage between production and utilization'],c:1,e:'MBSE uses models as central engineering artifacts to support multiple SE activities from concept through later life-cycle stages, improving consistency and communication when applied well.',r:'Chapter 4, §4.2.1, pp. 219–221'},
 {id:28,d:'tailoring',q:'How should agile and systems engineering relate?',a:['They are mutually exclusive','Agile removes the need for architecture and requirements','Agile principles can be integrated with SE through iterative learning, incremental delivery, and disciplined attention to the whole system','Agile is only a maintenance method'],c:2,e:'The handbook presents agile SE as an application approach that combines rapid learning and incremental evolution with systems thinking and technical discipline.',r:'Chapter 4, §4.2.2, pp. 221–224'},
 {id:29,d:'tailoring',q:'A brownfield or legacy-system effort most clearly differs from a greenfield effort because it:',a:['Has no stakeholders','Must account for existing capabilities, constraints, interfaces, data, and operational continuity','Never uses technical processes','Cannot be tailored'],c:1,e:'Legacy contexts inherit constraints, interfaces, technical debt, operational dependencies, and existing stakeholders. These shape analysis, architecture, transition, and risk decisions.',r:'Chapter 4, §4.3.1–4.3.2, pp. 229–231'},
 {id:30,d:'tailoring',q:'For a system of systems, a key engineering challenge is that constituent systems often:',a:['Have no independent purpose','Retain operational and managerial independence while contributing to broader capabilities','Share one lifecycle and one owner by definition','Cannot evolve after integration'],c:1,e:'Systems of systems involve constituent systems that can operate and be managed independently, creating challenges in authority, evolution, interfaces, emergence, and coordination.',r:'Chapter 4, §4.3.6, pp. 235–238'}
];
const labels={foundations:'Foundations & life cycles',processes:'Process groups',technical:'Technical processes',methods:'Analyses & methods',tailoring:'Tailoring & application',mixed:'Mixed handbook practice'};
const cram=[
 ['Need → stakeholder requirement → system requirement','A need expresses the desired outcome or problem in context. Stakeholder requirements formalize the stakeholder-oriented view. System requirements transform that view into the technical characteristics of a solution.','§2.3.5.1–2.3.5.3, pp. 103–118'],
 ['Architecture vs. design','Architecture defines concepts, structure, principles, properties, and relationships. Design adds enough detail to enable implementation in accordance with requirements and architecture.','§2.3.5.4–2.3.5.5, pp. 118–129'],
 ['Verification vs. validation','Verification asks whether specified requirements are fulfilled. Validation asks whether the system achieves intended use, mission/business objectives, and stakeholder needs in its operational environment.','§2.3.5.9 & §2.3.5.11, pp. 141–149'],
 ['MOE vs. MOP vs. TPM','MOEs address operational effectiveness; MOPs address system performance; TPMs track selected technical parameters and trends during development.','§2.3.4.7, pp. 93–98'],
 ['Iteration, recursion, concurrency','Iteration repeats activities to improve or resolve; recursion reapplies a process at successive system levels; concurrency means processes overlap and interact rather than forming one fixed sequence.','§2.3.1.2, pp. 42–44'],
 ['The four process groups','Agreement; Organizational Project-Enabling; Technical Management; Technical. The grouping is a framework—not a mandatory execution sequence.','§2.3.1, pp. 39–44'],
 ['Integration vs. transition','Integration combines elements and establishes their interactions. Transition places the verified system in its operational environment and establishes readiness for use.','§2.3.5.8 & §2.3.5.10, pp. 137–146'],
 ['Tailoring','Adapt process use to context, risk, complexity, system type, life cycle, standards, and agreements while retaining necessary outcomes and value-adding rigor.','§4.1, pp. 215–219'],
 ['Risk includes opportunity','Risk management addresses uncertain effects on objectives—both threats and opportunities—through planning, identification, analysis, treatment, and monitoring.','§2.3.4.4, pp. 81–87'],
 ['Six typical life-cycle stages','Concept, development, production, utilization, support, retirement. Organizations can adapt the model and decision gates to context.','§2.1.2, pp. 26–29']
];
const defaultState={attempts:0,correct:0,misses:[],confidence:{},domains:[]};
let state=Object.assign({},defaultState,JSON.parse(localStorage.getItem('asep-sprint')||'{}'));
let quiz=[],index=0,current=null,answered=false,mode='mixed';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('asep-sprint',JSON.stringify(state));updateStats()}
function updateStats(){
 const accuracy=state.attempts?Math.round(state.correct/state.attempts*100):0;
 $('#answered-total').textContent=state.attempts;$('#miss-count').textContent=state.misses.length;$('#retry-total').textContent=state.misses.length;
 $('#accuracy').textContent=state.attempts?accuracy+'%':'—';$('#coverage').textContent=`${state.domains.length}/5`;
 $('#mastery-value').textContent=accuracy+'%';$('#mastery-ring').style.background=`conic-gradient(#e7a060 ${accuracy*3.6}deg,#315b4d 0deg)`;
 $('#review-title').textContent=state.misses.length?`${state.misses.length} question${state.misses.length===1?'':'s'} ready to retry.`:'Your retry queue is clear.';
 $('#review-copy').textContent=state.misses.length?'Answer these again without notes. A correct, confident retry removes each item from the queue.':'Missed or low-confidence questions will collect here for a targeted second pass.';
 $('#review-action').innerHTML=state.misses.length?'Start retry session <span>→</span>':'Practice mixed questions <span>→</span>';
}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#view-title').textContent=name==='cram'?'Rapid review':name[0].toUpperCase()+name.slice(1);window.scrollTo(0,0);$('.sidebar').classList.remove('open')}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function startQuiz(topic='mixed',review=false){
 mode=review?'review':topic;let pool=review?questions.filter(q=>state.misses.includes(q.id)):(topic==='mixed'?questions:questions.filter(q=>q.d===topic));
 if(!pool.length){pool=questions;mode='mixed'}quiz=shuffled(pool).slice(0,topic==='mixed'?10:Math.min(8,pool.length));index=0;
 $('#quiz-title').textContent=review?'Retry your misses':labels[topic]||labels.mixed;$('#quiz-kicker').textContent=review?'TARGETED RETRIEVAL':'FOCUSED PRACTICE';showView('practice');renderQuestion();
}
function renderQuestion(){
 if(index>=quiz.length){finishQuiz();return}current=quiz[index];answered=false;$('#question-number').textContent=`${index+1} / ${quiz.length}`;$('#quiz-bar').style.width=`${(index+1)/quiz.length*100}%`;$('#question-domain').textContent=labels[current.d].toUpperCase();$('#question-text').textContent=current.q;$('#feedback').hidden=true;
 $('#answers').innerHTML=current.a.map((x,i)=>`<button class="answer" data-answer="${i}"><b>${String.fromCharCode(65+i)}</b><span>${x}</span></button>`).join('');$$('.answer').forEach(b=>b.addEventListener('click',()=>answer(+b.dataset.answer)));$$('.confidence button').forEach(b=>b.classList.remove('selected'));
}
function answer(choice){
 if(answered)return;answered=true;state.attempts++;const ok=choice===current.c;if(ok)state.correct++;else if(!state.misses.includes(current.id))state.misses.push(current.id);if(!state.domains.includes(current.d))state.domains.push(current.d);
 $$('.answer').forEach((b,i)=>{b.disabled=true;if(i===current.c)b.classList.add('correct');if(i===choice&&!ok)b.classList.add('wrong')});$('#feedback').hidden=false;$('#feedback-icon').textContent=ok?'✓':'!';$('#feedback-heading').textContent=ok?'Correct — lock in the distinction.':'Not quite — retrieve the rationale.';$('#feedback-icon').style.background=ok?'var(--mint)':'#fae4df';$('#feedback-icon').style.color=ok?'var(--green)':'var(--red)';$('#explanation').textContent=current.e;$('#reference').textContent=current.r;save();
}
function finishQuiz(){showView('dashboard');const hero=$('.hero');hero.animate([{transform:'scale(.99)',opacity:.75},{transform:'scale(1)',opacity:1}],{duration:400});}
$$('.nav-item').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));$('.menu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$('#start-practice').addEventListener('click',()=>startQuiz('mixed'));$('#quit-quiz').addEventListener('click',()=>showView('dashboard'));$('#next-question').addEventListener('click',()=>{index++;renderQuestion()});
$$('[data-topic]').forEach(b=>b.addEventListener('click',()=>startQuiz(b.dataset.topic)));$$('[data-review]').forEach(b=>b.addEventListener('click',()=>state.misses.length?startQuiz('mixed',true):showView('review')));$$('[data-cram]').forEach(b=>b.addEventListener('click',()=>showView('cram')));$('#review-action').addEventListener('click',()=>startQuiz('mixed',state.misses.length>0));
$$('.confidence button').forEach(b=>b.addEventListener('click',()=>{const level=+b.dataset.confidence;state.confidence[current.id]=level;$$('.confidence button').forEach(x=>x.classList.toggle('selected',x===b));if(level===3&&current.c===+$('.answer.correct').dataset.answer)state.misses=state.misses.filter(id=>id!==current.id);else if(level<2&&!state.misses.includes(current.id))state.misses.push(current.id);save()}));
$('#cram-grid').innerHTML=cram.map(([q,a,r])=>`<article class="cram-card"><button>${q}<span>＋</span></button><div class="cram-answer">${a}<b>HANDBOOK ${r}</b></div></article>`).join('');$$('.cram-card button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.classList.toggle('open');b.querySelector('span').textContent=b.parentElement.classList.contains('open')?'−':'＋'}));
updateStats();
